[package]

name = "grust-GObject-2_0"
version = "0.0.1-dev"
authors = ["Mikhail Zabaluev <mikhail.zabaluev@gmail.com"]
license = "LGPL-2.1+"

[lib]
name = "grust-GObject-2_0"
path = "gobject.rs"

[dependencies.grust]
git = "https://github.com/gi-rust/grust.git"

[dependencies.grust-GLib-2_0]
path = "../glib"

[dependencies.gobject-2_0-sys]
git = "https://github.com/gi-rust/gobject-sys.git"
